import { Picture } from './picture';
import * as path from 'path';

export const picturesList: Picture[] = [
    {
        title: 'Banana',
        year: 2022,
        price: 100,
        author: 'Vasilisa',
        brush: 'oil',
        description: 'Banana painted with oil brush',
        amount: 1,
        color: 'yellow',
        url: path.join(__dirname, '/assets/img/banana-oil-brush.jpg'),
    },
    {
        title: 'Cat',
        year: 2021,
        price: 105,
        author: 'Valiantsina',
        brush: 'pencil',
        description: 'Grey cat smiles you',
        amount: 10,
        color: 'grey',
        url: path.join(__dirname, '/assets/img/cat-pencil.jpg'),
    },
    {
        title: 'Christmas tree',
        year: 2023,
        price: 70,
        author: 'Vasilisa',
        brush: 'oil',
        description: 'Holiday is coming! Christmas tree for you HO-HO-HO',
        amount: 2,
        color: 'green',
        url: path.join(__dirname, '/assets/img/christmas-tree-oil-brush.jpg'),
    },
    {
        title: 'Cloud',
        year: 2022,
        price: 50,
        author: 'Valiantsina',
        brush: 'pencil',
        description: 'A little cloud for warm days',
        amount: 15,
        color: 'blue',
        url: path.join(__dirname, '/assets/img/cloud-pencil.jpg'),
    },
    {
        title: 'Fish',
        year: 2018,
        price: 10,
        author: 'Vasilisa',
        brush: 'crayon',
        description: 'The best quiet pet or just cookie, as you wish',
        amount: 3,
        color: 'orange',
        url: path.join(__dirname, '/assets/img/fish-crayon.jpg'),
    },
    {
        title: 'Flower',
        year: 2018,
        price: 5,
        author: 'Valiantsina',
        brush: 'pencil',
        description: 'Your winter bouquet',
        amount: 9,
        color: 'blue',
        url: path.join(__dirname, '/assets/img/flower-pencil.jpg'),
    },
    {
        title: 'Grape',
        year: 2019,
        price: 200,
        author: 'Vasilisa',
        brush: 'watercolor',
        description: 'Just delicious',
        amount: 1,
        color: 'purple',
        url: path.join(__dirname, '/assets/img/grape-watercolor-brush.jpg'),
    },
    {
        title: 'Grass',
        year: 2022,
        price: 73,
        author: 'Valiantsina',
        brush: 'pencil',
        description: 'Smells like summer',
        amount: 4,
        color: 'green',
        url: path.join(__dirname, '/assets/img/grass-pencil.jpg'),
    },
    {
        title: 'Heart',
        year: 2020,
        price: 70,
        author: 'Vasilisa',
        brush: 'airbrush',
        description: 'All you need is love',
        amount: 8,
        color: 'red',
        url: path.join(__dirname, '/assets/img/heart-airbrush.jpg'),
    },
    {
        title: 'Orange',
        year: 2019,
        price: 44,
        author: 'Vasilisa',
        brush: 'marker',
        description: 'Orange like orange',
        amount: 8,
        color: 'orange',
        url: path.join(__dirname, '/assets/img/orange-marker.jpg'),
    },
    {
        title: 'Pig',
        year: 2016,
        price: 13,
        author: 'Vasilisa',
        brush: 'marker',
        description: 'Oink oink',
        amount: 3,
        color: 'rose',
        url: path.join(__dirname, '/assets/img/pig-marker.jpg'),
    },
    {
        title: 'Rainbow',
        year: 2020,
        price: 180,
        author: 'Vasilisa',
        brush: 'crayon',
        description: 'ROYGBIV',
        amount: 1,
        color: 'rainbow',
        url: path.join(__dirname, '/assets/img/rainbow-crayon.jpg'),
    },
    {
        title: 'Star',
        year: 2021,
        price: 29,
        author: 'Vasilisa',
        brush: 'pencil',
        description: 'Shine bright',
        amount: 13,
        color: 'yellow',
        url: path.join(__dirname, '/assets/img/star-pencil.jpg'),
    },
    {
        title: 'Sun',
        year: 2019,
        price: 30,
        author: 'Valiantsina',
        brush: 'crayon',
        description: 'For rainy days',
        amount: 30,
        color: 'yellow',
        url: path.join(__dirname, '/assets/img/sun-crayon.jpg'),
    },
    {
        title: 'Watermelon',
        year: 2022,
        price: 90,
        author: 'Vasilisa',
        brush: 'marker',
        description: "You can't just stop",
        amount: 12,
        color: 'red',
        url: path.join(__dirname, '/assets/img/watermelon-marker.jpg'),
    },
    {
        title: 'Dog',
        year: 2015,
        price: 100,
        author: 'Veranika',
        brush: 'watercolor',
        description: 'Your best friend',
        amount: 1,
        color: 'grey',
        url: path.join(__dirname, '/assets/img/dog-watercolor-brush.jpg'),
    },
    {
        title: 'Rocket',
        year: 2016,
        price: 200,
        author: 'Veranika',
        brush: 'brush',
        description: 'To the moon',
        amount: 15,
        color: 'grey',
        url: path.join(__dirname, '/assets/img/rocket-brush.jpg'),
    },
    {
        title: 'Saturn',
        year: 2016,
        price: 100,
        author: 'Veranika',
        brush: 'marker',
        description: 'Just too far away',
        amount: 5,
        color: 'brown',
        url: path.join(__dirname, '/assets/img/saturn-marker.jpg'),
    },
    {
        title: 'Snail',
        year: 2017,
        price: 102,
        author: 'Veranika',
        brush: 'oil',
        description: 'Slo-o-o-o-ow',
        amount: 15,
        color: 'brown',
        url: path.join(__dirname, '/assets/img/snail-oil-brush.jpg'),
    },
    {
        title: 'Tree',
        year: 2018,
        price: 52,
        author: 'Veranika',
        brush: 'crayon',
        description: 'Perfect shadow and air',
        amount: 15,
        color: 'green',
        url: path.join(__dirname, '/assets/img/snail-oil-brush.jpg'),
    },
];
