import { Picture } from './picture.inteface';

export const picturesList: Picture[] = [
    {
        title: 'Banana',
        year: 2022,
        price: 100,
        author: 'Vasilisa',
        brush: 'oil',
        description: 'Banana painted with oil brush',
        amount: 1,
        color: 'yellow',
        url: './assets/img/banana-oil-brush.jpg',
        onsale: false,
    },
    {
        title: 'Cat',
        year: 2021,
        price: 105,
        author: 'Valiantsina',
        brush: 'pencil',
        description: 'Grey cat smiles you',
        amount: 10,
        color: 'grey',
        url: './assets/img/cat-pencil.jpg',
        onsale: false,
    },
    {
        title: 'Triangles',
        year: 2021,
        price: 77,
        author: 'Valiantsina',
        brush: 'watercolor',
        description: 'Blue triangles filled with watercolor',
        amount: 3,
        color: 'blue',
        url: './assets/img/triangles-blue-watercolor.jpg',
        onsale: false,
    },
    {
        title: 'Christmas tree',
        year: 2023,
        price: 70,
        author: 'Vasilisa',
        brush: 'oil',
        description: 'Holiday is coming! Christmas tree for you HO-HO-HO',
        amount: 2,
        color: 'green',
        url: './assets/img/christmas-tree-oil-brush.jpg',
        onsale: false,
    },
    {
        title: 'Cloud',
        year: 2022,
        price: 50,
        salePrice: 40,
        author: 'Valiantsina',
        brush: 'pencil',
        description: 'A little cloud for warm days',
        amount: 15,
        color: 'blue',
        url: './assets/img/cloud-pencil.jpg',
        onsale: true,
    },
    {
        title: 'Fish',
        year: 2018,
        price: 10,
        author: 'Vasilisa',
        brush: 'crayon',
        description: 'The best quiet pet or just cookie, as you wish',
        amount: 3,
        color: 'orange',
        url: './assets/img/fish-crayon.jpg',
        onsale: false,
    },
    {
        title: 'Flower',
        year: 2018,
        price: 5,
        author: 'Valiantsina',
        brush: 'pencil',
        description: 'Your winter bouquet',
        amount: 9,
        color: 'blue',
        url: './assets/img/flower-pencil.jpg',
        onsale: false,
    },
    {
        title: 'Grape',
        year: 2019,
        price: 200,
        salePrice: 130,
        author: 'Vasilisa',
        brush: 'watercolor',
        description: 'Just delicious',
        amount: 1,
        color: 'purple',
        url: './assets/img/grape-watercolor-brush.jpg',
        onsale: true,
    },
    {
        title: 'Stars',
        year: 2018,
        price: 90,
        author: 'Valiantsina',
        brush: 'pencil',
        description: 'Yellow stars',
        amount: 3,
        color: 'yellow',
        url: './assets/img/stars-yellow-pencil.jpg',
        onsale: false,
    },
    {
        title: 'Grass',
        year: 2022,
        price: 73,
        author: 'Valiantsina',
        brush: 'pencil',
        description: 'Smells like summer',
        amount: 4,
        color: 'green',
        url: './assets/img/grass-pencil.jpg',
        onsale: false,
    },
    {
        title: 'Heart',
        year: 2020,
        price: 70,
        author: 'Vasilisa',
        brush: 'airbrush',
        description: 'All you need is love',
        amount: 8,
        color: 'red',
        url: './assets/img/heart-airbrush.jpg',
        onsale: false,
    },
    {
        title: 'Pentagon',
        year: 2010,
        price: 80,
        author: 'Valiantsina',
        brush: 'pencil',
        description: 'Green pentagon',
        amount: 3,
        color: 'green',
        url: './assets/img/pentagon-green-pencil.jpg',
        onsale: false,
    },
    {
        title: 'Orange',
        year: 2019,
        price: 44,
        salePrice: 40,
        author: 'Vasilisa',
        brush: 'marker',
        description: 'Orange like orange',
        amount: 8,
        color: 'orange',
        url: './assets/img/orange-marker.jpg',
        onsale: true,
    },
    {
        title: 'Pig',
        year: 2016,
        price: 13,
        author: 'Vasilisa',
        brush: 'marker',
        description: 'Oink oink',
        amount: 3,
        color: 'rose',
        url: './assets/img/pig-marker.jpg',
        onsale: false,
    },
    {
        title: 'Rainbow',
        year: 2020,
        price: 180,
        salePrice: 100,
        author: 'Vasilisa',
        brush: 'crayon',
        description: 'ROYGBIV',
        amount: 1,
        color: 'rainbow',
        url: './assets/img/rainbow-crayon.jpg',
        onsale: true,
    },
    {
        title: 'Star',
        year: 2021,
        price: 29,
        author: 'Vasilisa',
        brush: 'pencil',
        description: 'Shine bright',
        amount: 13,
        color: 'yellow',
        url: './assets/img/star-pencil.jpg',
        onsale: false,
    },
    {
        title: 'Sun',
        year: 2019,
        price: 30,
        author: 'Valiantsina',
        brush: 'crayon',
        description: 'For rainy days',
        amount: 30,
        color: 'yellow',
        url: './assets/img/sun-crayon.jpg',
        onsale: false,
    },
    {
        title: 'Watermelon',
        year: 2022,
        price: 90,
        author: 'Vasilisa',
        brush: 'marker',
        description: "You can't just stop",
        amount: 12,
        color: 'red',
        url: './assets/img/watermelon-marker.jpg',
        onsale: false,
    },
    {
        title: 'Dog',
        year: 2015,
        price: 100,
        salePrice: 95,
        author: 'Veranika',
        brush: 'watercolor',
        description: 'Your best friend',
        amount: 1,
        color: 'grey',
        url: './assets/img/dog-watercolor-brush.jpg',
        onsale: true,
    },
    {
        title: 'Rocket',
        year: 2016,
        price: 200,
        salePrice: 180,
        author: 'Veranika',
        brush: 'brush',
        description: 'To the moon',
        amount: 15,
        color: 'grey',
        url: './assets/img/rocket-brush.jpg',
        onsale: true,
    },
    {
        title: 'Saturn',
        year: 2016,
        price: 100,
        author: 'Veranika',
        brush: 'marker',
        description: 'Just too far away',
        amount: 5,
        color: 'brown',
        url: './assets/img/saturn-marker.jpg',
        onsale: false,
    },
    {
        title: 'Snail',
        year: 2017,
        price: 102,
        author: 'Veranika',
        brush: 'oil',
        description: 'Slo-o-o-o-ow',
        amount: 15,
        color: 'brown',
        url: './assets/img/snail-oil-brush.jpg',
        onsale: false,
    },
    {
        title: 'Oval',
        year: 2010,
        price: 84,
        author: 'Valiantsina',
        brush: 'oil',
        description: 'Red oval',
        amount: 3,
        color: 'red',
        url: './assets/img/oval-red-oil.jpg',
        onsale: false,
    },
    {
        title: 'Tree',
        year: 2018,
        price: 52,
        author: 'Veranika',
        brush: 'crayon',
        description: 'Perfect shadow and air',
        amount: 15,
        color: 'green',
        url: './assets/img/tree-crayon.jpg',
        onsale: false,
    },
    {
        title: 'Squares',
        year: 2012,
        price: 45,
        author: 'Valiantsina',
        brush: 'crayon',
        description: 'Black squares',
        amount: 3,
        color: 'black',
        url: './assets/img/squares-black-crayon.jpg',
        onsale: false,
    },
];
